#ifndef _BUILD_H_
#define _BUILD_H_


#define VERSION_MAJOR "1"
#define VERSION_MINOR "6"
#define VERSION_PATCH "0"
#define VERSION_NAME "Pork1"
#define VERSION_STRING VERSION_MAJOR "." VERSION_MINOR "." VERSION_PATCH "-" VERSION_NAME


#endif // _BUILD_H_
